language: java
sudo: false
env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
    - NODE_VERSION=10.16.3 CC=clang CXX=clang++

before_install:
  - nvm install $NODE_VERSION

script:
  - mvn clean install -P full
  - cd features && mvn karaf:kar && cd ..
  - ls

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "features/target/features-1.0-SNAPSHOT.kar"
  skip_cleanup: true
  on:
    tags: true
