language: java
sudo: false
env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
    - NODE_VERSION=10.16.3 CC=clang CXX=clang++

before_install:
  - nvm install $NODE_VERSION

script:
  - mvn clean install -P full
  - mvn -f features/pom.xml install karaf:kar
  - mkdir temp
  - mkdir build
  - cp features/target/features-1.0-SNAPSHOT.kar ./temp/
  - cp -r scripts/aws/* ./temp
  - zip -r ./build/timeboard.zip ./temp/*



deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    local_dir: "build"
    bucket: "$AWS_BUCKET"
    region: eu-west-1
    skip_cleanup: true
    on:
      branch: develop