language: java
sudo: false
env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
    - NODE_VERSION=10.16.3 CC=clang CXX=clang++

before_install:
  - nvm install $NODE_VERSION

script:
  - sh eb.sh

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    local_dir: "build"
    bucket: "$AWS_BUCKET"
    region: eu-west-1
    skip_cleanup: true
    on:
      branch: spring