language: java
sudo: false
env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
    - NODE_VERSION=10.16.3 CC=clang CXX=clang++

before_install:
  - nvm install $NODE_VERSION

script:
  - sh eb.sh

deploy:
  - provider: elasticbeanstalk
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    region: "eu-west-1"
    app: "TimeboardApp"
    env: "TimeboardEnvironment"
    zip_file: "build/timeboard.$TRAVIS_COMMIT.zip"
    bucket_name: "$AWS_BUCKET"
    skip_cleanup: true
    on:
      branch: master