AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DBUser:
    Type: 'String'
  DBPassword:
    Type: 'String'
  DatabaseDNSName:
    Type: 'String'
  DBSubnetA:
    Type: 'AWS::EC2::Subnet::Id'
  DBSubnetB:
    Type: 'AWS::EC2::Subnet::Id'
  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup::Id'
  Route53HostedZone:
    Type: 'AWS::Route53::HostedZone::Id'
Resources:

  MySQLDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: '30'
      StorageType: 'gp2'
      PubliclyAccessible: 'false'
      DBInstanceClass: 'db.t2.micro'
      DBName: 'Timeboard'
      Engine: MySQL
      BackupRetentionPeriod: 0
      EngineVersion: '8.0.16'
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName:
        Ref: DBSubnetGroup
      MasterUserPassword:
        Ref: DBPassword
      MasterUsername:
        Ref: DBUser

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'Timeboard DBSubnet'
      SubnetIds:
        - Ref: DBSubnetA
        - Ref: DBSubnetB
  DBDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref 'Route53HostedZone'
      Comment: DNS name for timeboard
      Name: !Ref 'DatabaseDNSName'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !GetAtt MySQLDatabase.Endpoint.Address

Outputs:
  MySQLDNS:
    Description: Databse DNS Name
    Value: !GetAtt MySQLDatabase.Endpoint.Address
  MySQLPort:
    Description: Databse Prot
    Value: !GetAtt MySQLDatabase.Endpoint.Port
