@startuml

database mysql

node "JVM 11" {
    node "Spring App"{

     [core] -- mysql
     [account] -- core
     [account] -- [core-ui]
     [projects] -- core
     [timesheet] -- core
     [home] -- core
     [organization] -- core
     [organization] -- [core-ui]
     [reporting] -- core
     [reporting] -- [core-ui]
     [projects] -- [core-ui]
     [timesheet] -- [core-ui]
     [home] -- [core-ui]

    }
}




@enduml