@startuml

database mysql

node "JVM 11" {
    node "Apache Karaf"{


         node "Kronops"{
             [core] -- mysql
             [security] -- core
             [security] -- [core-ui]
             [projects] -- core
             [timesheet] -- core
             [home] -- core
             [shell] -- core
             [projects] -- [core-ui]
             [timesheet] -- [core-ui]
             [home] -- [core-ui]


         }



         [JPA] ---- core
         [JTA] --- core
         [JNDI] --- core

         ["Http Whiteboard"] --- [core-ui]
    }
}




@enduml