@startuml

Organization "1" -- "*" OrganizationMembership
User "1" -- "1..*" OrganizationMembership
User "1" -- "*" ProjectMembership
Project "1" -- "*" ProjectMembership
ProjectRole "1" -- "1" ProjectMembership
OrganizationMembership  -- "1" OrganizationRole

ProjectToOrganization "1..*" -- "1" Project
ProjectToOrganization "*" -- "1" Organization

enum OrganizationRole {
    LEADER,
    MANAGER,
    EMPLOYEE
}

enum ProjectRole {
    OWNER,
    CONTRIBUTOR
}

@enduml