@startuml

(Create project) --- :Actor:
(Create cluster) -- :Actor:
(Add project's member) -- :Project Owner:
(Add project to cluster) --- :Project Owner:
(Enter values in timesheet) --- :Project Member:
(Enter values in timesheet) --- :Project Owner:
(Validate timesheet) - :Project Member:
(Validate timesheet) -- :Project Owner:
(Create task) - :Project Member:
(Create task) --- :Project Owner:
(Assign task to Project Member) ---- :Project Owner:
(View projet Gantt) - :Project Member:
(View projet Gantt) --- :Project Owner:

@enduml